common: add issues found by nolintlint
Fix issued found by nolintlint (mostly removal of nolint annotation).
Explain what or why we're suppressing a warning for a few cases.

Unfortunately, enabling nolintlint itself in CI results in bogus
warnings like these:

>  Error: /home/runner/work/container-libs/container-libs/common/libimage/manifests/manifests.go:960:83: directive `//nolint:staticcheck // suppress "lockfile.Locker is deprecated".` is unused for linter "staticcheck" (nolintlint)
>  func LockerForImage(store storage.Store, image string) (lockfile.Locker, error) { //nolint:staticcheck // suppress "lockfile.Locker is deprecated".
>                                                                                    ^
>  Error: /home/runner/work/container-libs/container-libs/common/pkg/formats/templates.go:23:29: directive `//nolint:staticcheck` is unused for linter "staticcheck" (nolintlint)
>  	"title":    strings.Title, //nolint:staticcheck
>  	                           ^
>  Error: /home/runner/work/container-libs/container-libs/common/pkg/report/template.go:51:29: directive `//nolint:staticcheck` is unused for linter "staticcheck" (nolintlint)
>  	"title":    strings.Title, //nolint:staticcheck
>                                  ^

so let's keep it off the list of enabled linters.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>